name: upload to next cloud
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to Nextcloud
      uses: appleboy/ftp-upload-action@v3
      with:
        url: ${{ secrets.NEXTCLOUD_URL }}
        username: ${{ secrets.NEXTCLOUD_USERNAME }}
        password: ${{ secrets.NEXTCLOUD_PASSWORD }}
        server-protocol: ftp
        source: "my_context_file.yml"
        target: "Documents/ff"
