name: DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest


    # env:
    #   WEBSITE: "https://remittance.v1.fintechsys.net"
    #   LOGIN_URL: "https://remittance.v1.fintechsys.net/admin/"
    #   AUTH_USERNAME: "admin"
    #   AUTH_PASSWORD: "admin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZAP
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-full-scan.py -I -j -m 10 -T 60 \
            -t https://remittance.v1.fintechsys.net/admin/' \
            -r testreport.html \
            --hook=/zap/auth_hook.py \
            -z "auth.loginurl=https://remittance.v1.fintechsys.net/admin/ \
                auth.username="admin" \
                auth.password="admin" \
                auth.username_field="username" \
                auth.password_field="password" \
                auth.submit_field="submit" \
                auth.exclude=".*logout.*,http://url.com/somepath.*" \
                auth.include="https://api.website.net.*"


     
