name: DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    
    services:
       zap:
          image: owasp/zap2docker-stable:2.11.0
          ports:
            - 8080:8080


    env:
      WEBSITE: "https://remittance.v1.fintechsys.net"
      LOGIN_URL: "https://remittance.v1.fintechsys.net/admin/"
      AUTH_USERNAME: "admin"
      AUTH_PASSWORD: "admin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZAP
        run: |
          mkdir /zap/wrk/
          zap-baseline.py -J gl-dast-report.json -t $WEBSITE \
            --auth-url $LOGIN_URL \
            --auth-username "$AUTH_USERNAME" \
            --auth-password "$AUTH_PASSWORD" || true
          cp /zap/wrk/gl-dast-report.json .

      - name: Upload DAST report
        uses: actions/upload-artifact@v2
        with:
          name: dast-report
          path: gl-dast-report.json
