name: download2 art
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: .github/workflows/
    - name: Display structure of downloaded files
      run: ls -R github/workflows/
