name: Download artfiacts
on:
  workflow_dispatch:
  
jobs:
 DOwnload_artficat:
    runs-on: ubuntu-latest
    # permissions: write-all
    # name: Scan the webapplication
    steps:
      # Checkout your repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Download artifact from the previous workflow run
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Zap_Report_22   # Replace with your artifact name

      # Upload to Nextcloud
      - name: Upload to Nextcloud
        run: |
          curl -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
               -T Zap_Report_22 \
               "https://nextcloud.fintechsys.net/index.php/webdav/Documents/ff/"
        env:
          NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USERNAME }}
          NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}

    # steps:
    
    # - uses: actions/checkout@v2

    # - name: Upload files to Nextcloud
    #   run: |
    #     curl -u ${{ secrets.NEXTCLOUD_USER }}:${{ secrets.NEXTCLOUD_PASSWORD }} -T .github/workflows/my_context_file https://nextcloud.fintechsys.net/index.php/apps/files/falah/Documents/ff/


      
    # - 
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: Zap_Report_22 
    # -
    #   name: Decompress artifact
    #   run: tar -xvf Zap_Report_22.tar.gz
    # -
    #   name: Show files
    #   run: ls -l Zap_Report_22
    # -
    #   name: Upload files
    #   run: |
    #     for FILE in Zap_Report_22/*
    #     do
    #       echo "Uploading file: $FILE"
    #       curl \
    #         -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
    #         -T "$FILE" \
    #         -g ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/
    #     done
      
