name: Create a new tag

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Create version.txt if it doesn't exist
      - name: Create version.txt
        run: |
          if [ ! -f version.txt ]; then
            echo "v1.0.0" > version.txt
          fi

      # Increment the patch version and create a new tag with timestamp
      - name: Increment Patch Version and Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read the current version from the version file
          current_version=$(cat version.txt)

          # Extract major, minor, and patch components
          if [[ $current_version =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
          else
            # If the version file does not follow semantic versioning, set default values
            major=1
            minor=0
            patch=0
          fi

          # Increment the patch version
          ((patch++))

          # Create a unique tag with timestamp
          new_version="v$major.$minor.$patch-$(date +%Y%m%d%H%M%S)"
          echo "$new_version" > version.txt

          # Create the new tag and push it
          git tag "$new_version"
          git push origin "$new_version"


