name: Create a new tag

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create version.txt if it doesn't exist
        run: |
          if [ ! -f version.txt ]; then
            echo "v1.0.0" > version.txt
          fi

      - name: Increment Patch Version and Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          set -x
          current_version=$(cat version.txt)
          if [[ $current_version =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
          else
            # If the version file does not follow semantic versioning, set default values
            major=1
            minor=0
            patch=0
          fi
           patch=$((patch + 1))
          new_version="v$major.$minor.$patch"
          echo "$new_version" > version.txt
      
          git tag "$new_version"
          git push origin "$new_version"
        # new_version="v$major.$minor.$patch"
        # echo "$new_version" > version.txt
    
        # Add some debugging information
          # echo "current_version: $current_version"
          # echo "new_version: $new_version"
      
          # # Try to create a tag and push it
          # git tag "$new_version"
          # if git push origin "$new_version"; then
          #   echo "Tag and push succeeded"
          # else
          #   echo "Error: Failed to push tag to origin."
          #   exit 1
          # fi
          # ((patch++))
      
         
        
