name: test
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  build-test:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload file to Nextcloud
      run: | 
        echo ${{ github.event.pull_request.html_url }}
        echo  ${{ github.event.pull_request.base.ref }}
        echo ${{ github.repository }}
        echo ${{ github.repository_basename }}
      #   curl -u $NEXTCLOUD_USERNAME:$NEXTCLOUD_PASSWORD -T .github/workflows/OWSAP_ZAP.yml https://nextcloud.fintechsys.net/remote.php/dav/files/$NEXTCLOUD_USERNAME/Documents/ff/
      # env:
      #   NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
      #   NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
