name: ZAP_2
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # env:
        #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
        # uses: zaproxy/action-full-scan@v0.8.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: Zap_Report_3n
          # artifact_name: Zap_Report_3233
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/'

  

  upload_job:
      needs: zap_scan
      runs-on: self-hosted
      # runs-on: ubuntu-latest
      # permissions: write-all
      steps:
        # - name: Checkout
        #   uses: actions/checkout@v2
        - uses: actions/upload-artifact@v2
          with:  
            name: Zap_Report_3233
            path: .github/
            


  Download-job:
    needs: upload_job
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    # permissions: write-all
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Download an artifact
        uses: actions/download-artifact@v3
        with:
          name: Zap_Report_3233
          path: .github/
          
          
      # - name: List files in the artifact directory
      #   run: ls -R .github/workflows/Zap_Report_200/
  

  # upload_to_Nextcloude:
  #   needs: Download-job
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       # Upload to Nextcloud
  #     - name: Upload to Nextcloud
  #       run: |
  #         curl -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
  #              -T report_html.html \
  #              https://nextcloud.fintechsys.net/index.php/apps/files/${{ secrets.NEXTCLOUD_USERNAME }}/?dir=/Documents/ff&fileid=8332
  build-test:
    needs: Download-job
    # needs: download-artifact
    # needs: Download-job
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    - name: Upload file to Nextcloud
      run: | 
         curl -u $NEXTCLOUD_USERNAME:$NEXTCLOUD_PASSWORD -T /root/actions-runner2/_work/Zap/Zap/report_json.json https://nextcloud.fintechsys.net/remote.php/dav/files/$NEXTCLOUD_USERNAME/Documents/ff/
      env:
        NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
        NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}


      # - name: Send Email with Artifact
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: mail.fintechsys.net
      #     server_port: 465
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: Automated Artifact
      #     html_body: file://report_html.html
      #     body: Build artifact attached.
      #     to: ${{ secrets.USERS_EMAILS }}
      #     from: f.alfalahi@fintechsys.net
      #     attachments: ${{ github.workspace }}/Zap_Report_2




          
  
  

          



 




