name: ZAP Full Scan
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # env:
        #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
        # uses: zaproxy/action-full-scan@v0.8.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: Scan Results2
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/'
      - uses: actions/checkout@v2
  
      # Add steps to build your artifact here
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/your/artifact
  
      - name: Send Email with Artifact
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Automated Artifact
          body: Build artifact attached.
          to: recipient@example.com
          from: sender@example.com
          attachments: path/to/your/artifact
