name: ZAP_2
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # env:
        #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
        # uses: zaproxy/action-full-scan@v0.8.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: Scan Results_22
          artifact_name: Zap_Report_22
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/'


      - uses: actions/download-artifact@v4
        with:
          name: Zap_Report_22
          path: .github
      - name: Display structure of downloaded files
        run: ls -R .github
      # - name: Send Email with Artifact
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: mail.fintechsys.net
      #     server_port: 465
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: Automated Artifact
      #     html_body: file://report_html.html
      #     body: Build artifact attached.
      #     to: ${{ secrets.USERS_EMAILS }}
      #     from: f.alfalahi@fintechsys.net
      #     attachments: ${{ github.workspace }}/Zap_Report_2


      # - name: Upload to Nextcloud
      #   uses: MarcinOrlowski/nextcloud-upload-file@v1
      #   with:
      #     url: https://nextcloud.fintechsys.net/index.php/apps/files/?dir=/&fileid=3723
      #     username: ${{ secrets.NEXTCLOUD_USERNAME }}
      #     password: ${{ secrets.NEXTCLOUD_PASSWORD }}
      #     local_file_path: report_html.html
      #     remote_file_path: /Documents/ff/report_html.html





      # - name: Nextcloud Artifact
      #   uses: trympet/nextcloud-artifacts-action@v2
      #   with:
      #     name: 'Zap_Report_2'                               
      #     path: dist
      #     # path: 'bin/**/*.exe'                                 
      #     nextcloud-url: 'https://nextcloud.fintechsys.net/index.php/apps/files/?dir=/&fileid=3723'        
      #     nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }} 
      #     nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}
