name: ZAP_2
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # env:
        #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
        # uses: zaproxy/action-full-scan@v0.8.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: Scan Results_26
          artifact_name: Zap_Report_26
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/'

      - name: dowmload
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/fal7w/Zap.git/actions/artifacts/${artifact.id}



          
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   # Add steps for your build process here
  #   - name: sleep
  #     run: |
  #       sleep 200
  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: Zap_Report_26
  #       path: path/to/your/artifact

  #   - name: Get Run ID
  #     run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
  
  get-artifact-url:
    needs: zap_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
  #       run: |
  #         echo "The artifact URL is: https://github.com/${{ github.repository }}/actions/runs/$RUN_ID"
  # Download_uplaod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: Zap_Report_25
  #     -
  #       name: Decompress artifact
  #       run: tar -xvf Zap_Report_25.tar.gz
  #     -
  #       name: Show files
  #       run: ls -l Zap_Report_25
  #     -
  #       name: Upload files
  #       run: |
  #         for FILE in Zap_Report_25/*
  #         do
  #           echo "Uploading file: $FILE"
  #           curl \
  #             -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
  #             -T "$FILE" \
  #             -g ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/
  #         done
      # run: ls -R .github
      # - name: Send Email with Artifact
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: mail.fintechsys.net
      #     server_port: 465
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: Automated Artifact
      #     html_body: file://report_html.html
      #     body: Build artifact attached.
      #     to: ${{ secrets.USERS_EMAILS }}
      #     from: f.alfalahi@fintechsys.net
      #     attachments: ${{ github.workspace }}/Zap_Report_2


      # - name: Upload to Nextcloud
      #   uses: MarcinOrlowski/nextcloud-upload-file@v1
      #   with:
      #     url: https://nextcloud.fintechsys.net/index.php/apps/files/?dir=/&fileid=3723
      #     username: ${{ secrets.NEXTCLOUD_USERNAME }}
      #     password: ${{ secrets.NEXTCLOUD_PASSWORD }}
      #     local_file_path: report_html.html
      #     remote_file_path: /Documents/ff/report_html.html





      # - name: Nextcloud Artifact
      #   uses: trympet/nextcloud-artifacts-action@v2
      #   with:
      #     name: 'Zap_Report_2'                               
      #     path: dist
      #     # path: 'bin/**/*.exe'                                 
      #     nextcloud-url: 'https://nextcloud.fintechsys.net/index.php/apps/files/?dir=/&fileid=3723'        
      #     nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }} 
      #     nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}
