name: ZAP Full Scan
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
      ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.BASIC_TOKEN }}
      ZAP_USERNAME: ${{ secrets.ZAP_USERNAME }}
      ZAP_PASSWORD: ${{ secrets.ZAP_PASSWORD }}
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/login/?next=/admin/'
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -u admin -p admin'
