name: ZAP Full Scan
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: 
    - ubuntu-latest
    # - self-hosted
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://erp.fintechsys.net/'
