name: ZAP Full Scan
on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    # env:
    #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
    permissions: write-all
    name: Scan the webapplication
    steps:
      # - name: command lin
      #   run: |
      #     export ZAP_AUTH_HEADER_VALUE="${{ env.ZAP_AUTH_HEADER_VALUE }}"
       # -e ZAP_AUTH_HEADER_VALUE="${ZAP_AUTH_HEADER_VALUE}"
      #     echo $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # env:
        #   ZAP_AUTH_HEADER_VALUE: Basic ${{ secrets.ZAP_BASIC_TOKEN }}
        # uses: zaproxy/action-full-scan@v0.8.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: Scan Results2
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://remittance.v1.fintechsys.net/admin/login/'
          # http_login_form: '/admin/login'
          # http_login_http_username: 'admin'
          # http_login_http_password: ${{ secrets.ZAP_USER_PW }}
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: ' -n auth_context.js -U admin'
